print("hello world")
print("Hi guyss")
print("Welcome to git")
print("This is my first commit")
print("This is my second commit")
print("This is my third commit")
print("This is my fourth commit")
print("This is my fifth commit")
print("This is my sixth commit")            